elixir-editors/language-elixir

snippets/language-elixir.cson
`defp` and `defprotocol` are both using the same trigger: `defp`. This means that the `defp` snippet is inaccessible. Since the trigger `defp` makes most sense in the context of the `defp` snippet, this pull request proposes that the `defprotocol` snippet trigger be changed to `defpro`.
=> fix `defp` and `defprotocol` snippet conflict

snippets/language-elixir.cson
Always when I write a ``do`` manually and press enter I get a ``@doc``
---
I added a ``do`` snippet to avoid that.
=> Add `do` snippet

grammars/elixir.cson, snippets/language-elixir.cson
I found that defoverridable do not gets highlighted like other keywords. I'm totally new to atom plugins, so please be patient.
I'm not sure about the snippet part....could someone please have a look?
=> added the grammar and snippet for defoverridable

settings/language-elixir.cson
If someone wants to create an anonymous function that has multiple clauses then we should indent the next line for them so that everything looks correct.
Fixes #18
=> Index the `fn` pattern

snippets/language-elixir.cson
Analogous to `ii` for `IO.inspect`, this PR adds `ip` as `IO.puts`.
Thanks for the recent updates!
=> Add IO.puts snippet

grammars/elixir.cson
This change calls out elixir's [directives](http://elixir-lang.org/getting-started/alias-require-and-import.html) as so called `special-methods` which allows them to be themed separately from other control keywords.
=> Match directives

grammars/elixir.cson, snippets/language-elixir.cson
Highlight function declarations properly. Later we can use this initial pattern to match arguments to functions as well.
~~Currently this only matches `def` and `defp`. It would also make sense to match `defmacro` and `defmacrop`.~~ The match works for both function and macro definitions.
As part of this change I've also updated the function and macro snippets to add a default name. Without this the match registers the `do` as the definition which can look odd. Adding an default name conveniently solves this issue while also being more explicit.
=> Basic matching for function definitions

grammars/elixir.cson
Since keywords are just atoms, they should be highlighted as atoms.
=> Match keywords as atoms.

snippets/language-elixir.cson
Due to ordering issues in atom the `doc` snippet needs to be above the `do` snippet. Otherwise typing `do` and hitting tab or enter expands the `doc` snippet.
Fixes #40.
=> Order do snippet after the doc snippet

snippets/language-elixir.cson
As per @keathley’s suggestion, this PR uses `idef` and `idefp` as triggers for the inline snippets.
=> Add snippets for inline def and defp

grammars/elixir.cson
Currently heredocs aren't being scoped to elixir. This fix addresses that issue.
=> Scope comment documentation to elixir

grammars/elixir.cson, spec/elixir-spec.coffee
Doing some re-ordering of matches symbol highlighting was broken. I've fixed the ordering and also added tests for symbols.
=> Fix regression with symbol highlighting

grammars/elixir.cson, spec/elixir-spec.coffee
This change allows highlighting of TODOs and FIXMEs, etc. with the atom/language-todo package. I've also submitted a PR to them to enable snippets in elixir source as well: atom/language-todo#43
Fixes #45
=> Allow TODO highlighting in '#' comments.

settings/language-elixir.cson
Any new line after an `=` will now be indented:
```elixir
some_var =
data
|> foo
|> bar
```
Closes #55
=> Indent new lines that follow an equals sign.

grammars/elixir.cson, spec/elixir-spec.coffee
`case` (and other control structures) are always being matched as keywords even when they are used as atoms or variables. I've moved the matching so that atoms are now matched before control structures which should solve the first problem. Control keywords that are being used as a variable will still highlight as keywords which I'm personally OK with because it highlights to the user that they are doing something that has the potential to cause confusion. I'm willing to discuss that point if others feel strongly.
Closes #53
=> Match atoms before control structures.

grammars/elixir.cson, spec/elixir-spec.coffee
Fully support all of elixir's default sigils `~r, ~R, ~w, ~W, ~c, ~C, ~s, ~S` and parse them as their correct types.
Closes #57, #38
=> Full sigil support

grammars/elixir.cson, spec/elixir-spec.coffee
Based on #64.
Unused variables will be highlighted as a comment. Currently this is just a proof of concept to make sure that everything works correctly. There may be unforeseen side-effects from marking a variable as a comment.
=> Mark any unused variables as comments

grammars/elixir.cson, spec/elixir-spec.coffee
Fixes the issue described in #72.
Example of issue:
I've added specific selectors for using interpolated and literal string sigils with doc attributes since we want to render them as comments. I've also added support for using heredoc (triple single quotes or triple double quotes) as delimiters for all sigils. The end result is that all sigils that use heredocs as delimiters will be highlighted correctly and all string heredocs after doc attributes will be highlighted correctly as comments.
=> Interpolate sigils with heredoc delimiters.

grammars/elixir.cson, spec/elixir-spec.coffee
Based on #66.
Added selectors to unused variables and the single underscore while keeping the comment selector.
It also matches unused variables ending in exclamation and question mark.
=> Add unused and wildcard variables

snippets/language-elixir.cson
This PR adds [IEx.pry/1](https://hexdocs.pm/iex/IEx.html#pry/1) as a snippet. It complements `IO.inspect`and `IO.puts` snippets for debugging.
```elixir
require IEx
IEx.pry()
```
This is mainly a convenience to rapidly insert both lines. If a user doesn't need `require IEx`, they can autocomplete `IEx.pry` directly.
=> Add IEx pry snippet

snippets/language-elixir.cson
This PR add a new snippet for `@moduletag` and `@tag` from [ExUnit.Case](https://hexdocs.pm/ex_unit/ExUnit.Case.html).
> Changed body for line break into the heredocs after openned
> ```elixir
> @moduledoc """
> |
> """
> ```
> This standard is present on official documentation and most exemples (less a `enter`)
:arrow_up_small:  Removed from this PR 1ecd2a2
=> Add snippet moduletag and  line break

grammars/elixir.cson
This pull request adds the words "and", "or", and "not" to the list of highlight keywords.
=> Add "and", "or", and "not" to the list of highlighted keywords

grammars/elixir.cson, spec/elixir-spec.coffee
Atoms can be defined using double/single-quotes, with arbitrary unicode (with erlang 20.x onwards; otherwise ascii? or Latin-1? I don't recall) strings.
When used as keys in keyword lists or maps, they can also be written in short-hand style.
```ex
Interactive Elixir (1.5.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :"foo bar"
:"foo bar"
iex(2)> ["foo bar": :baz]
["foo bar": :baz]
```
This PR introduces highlight support for latter; **double/single-quoted atoms used as keys** where colons are suffixed to strings.
Edit: Initially I proposed and introduced an idea to match all letters inside quotes, then warn for unescaped quotes inside.
Though it turned out it won't work well when there are multiple valid matches within a single line. So I scrapped that in 3ed4064
Current …
=> Capture double/single-quoted atoms used as keys in keyword lists or maps

snippets/language-elixir.cson
Makes it easier to add todo comments
I'd submit this change to language-todo, but they are not accepting PRs
to add support for more languages (https://github.com/atom/language-todo/pull/43).
=> Add language-todo snippets

grammars/elixir.cson
This pull request adds the words "in" to the list of highlight keywords. 
I somehow missed this one yesterday. :)
=> Add "in" to the list of highlighted keywords

grammars/elixir.cson, spec/elixir-spec.coffee
This pull request fixes an issue introduced in a0824b9 that caused syntax highlighting to break on certain strings and charlists. Specifically, strings containing an escaped double quote followed by a semicolon ```"\": "``` and charlists containing an escaped single quote followed by a semicolon ```'\': '```.
The files now render as:
=> Handle escaped characters inside string and charlist atoms

snippets/language-elixir.cson
Ability to generate [custom guards](https://hexdocs.pm/elixir/Kernel.html#defguard/1) was added in Elixir 1.6.  
These changes are adding snippets for `gefguard` and `defguardp`.
=> Add snippets for custom guards added in Elixir 1.6

grammars/elixir.cson
This pull request adds keyword support for `defguard` and `defguardp`, which were added to [Elixir v1.6](https://hexdocs.pm/elixir/Kernel.html#defguard/1) to simply guard macro generation.
=> Add keyword support for defguard and defguardp

snippets/language-elixir.cson
We weren't able to expand snippets correctly before due to a bug upstream in the snippet library and in atom. Those issues have all been fixed so now we can automatically expand snippets in a much more convenient way.
=> Expand doc snippets correctly

grammars/elixir.cson, spec/elixir-spec.coffee
Add ExUnit 'test' and 'describe' macros to grammar to support highlighting. Addresses [#106](https://github.com/elixir-editors/language-elixir/issues/106).
=> Issue 106: Add ExUnit "test" and "describe" macros to grammar
